version: '3.1'
services:
  zookeeper_analytics:
    image: wurstmeister/zookeeper
    hostname: zookeeper_analytics
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  kafka_analytics:
    image: wurstmeister/kafka
    hostname: kafka_analytics
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper_analytics
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_analytics:2181"
      KAFKA_BROKER_ID: "1"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  clickhouse_analytics:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      - kafka_analytics
    links:
      - kafka_analytics
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  app_analytics:
    container_name: app_analytics
    build: ./app/
    command: python3 ./server.py
    volumes:
      - ./app/src/:/usr/src/app
    ports:
      - "8091:8091"
    depends_on:
      - kafka_analytics
      - clickhouse_analytics
    links:
      - kafka_analytics
      - clickhouse_analytics
    environment:
      WORK_ENV: dev
      TZ: Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  nginx_analytics:
    container_name: nginx_analytics
    image: nginx:latest
    ports:
      - "80:8090"
    volumes:
      - ./app/src/:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/app.conf:/etc/nginx/sites-enabled/app.conf:ro
    depends_on:
      - app_analytics
    links:
      - app_analytics
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"